url: https://vector341.github.io
theme: jekyll-theme-minimal
title: Vector's homepage
author: Vector341
description: Bookmark this to keep an eye on my project updates! To be filled.
show_excerpts: true
